### ISSUE TITLE
create datalist error

### ISSUE THREAD

**Issue by hnx1223** [ChanglongJiangGit/A2J-Transformer#15]
Thank you for your code! But I found there are some errors about the result of generating the datalist.  It's unable to read the images. Can you check the correctness of the code of generating datalist in dataset.py?

**Comment by ChanglongJiangGit** [comment]
Hello, can you give me a screenshot of the error report? This will help me find errors. Thanks!

**Comment by hnx1223** [comment]
You're so kind. If you are Chinese, we can use Chinese to communicate.&nbsp;










------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月20日(星期三) 下午4:14
收件人: ***@***.***&gt;; 
抄送: "Nanxuan ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ChanglongJiangGit/A2J-Transformer] create datalist error (Issue #15)





 
Hello, can you give me a screenshot of the error report? This will help me find errors. Thanks!

**Comment by ChanglongJiangGit** [comment]
可以的，方便给我看一下报错的截图，以及您的文件目录吗？

**Comment by hnx1223** [comment]
刚才那条邮件里面有截图，您有收到吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ChanglongJiangGit/A2J-Transformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月20日(星期三) 下午4:23
***@***.***&gt;;
抄送:&nbsp;"Nanxuan ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ChanglongJiangGit/A2J-Transformer] create datalist error (Issue #15)





 
可以的，方便给我看一下报错的截图，以及您的文件目录吗？

**Comment by ChanglongJiangGit** [comment]
没有收到23333可以再发一份吗？

**Comment by ChanglongJiangGit** [comment]
顺便，读不到图像大概率是数据集路径有问题，您可以看一下config.py文件中的interhand_anno_dir，interhand_images_path和cur_dir有没有正确修改，谢谢！

**Comment by hnx1223** [comment]
好的，这次在附件里哦，谢谢~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ChanglongJiangGit/A2J-Transformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月20日(星期三) 下午4:28
***@***.***&gt;;
抄送:&nbsp;"Nanxuan ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ChanglongJiangGit/A2J-Transformer] create datalist error (Issue #15)





 
没有收到23333可以再发一份吗？

**Comment by ChanglongJiangGit** [comment]
还是没有收到，可能是github的邮箱问题，您直接在github issue里面贴上截图吧，或者尝试直接发到我的邮箱，changlongj@hust.edu.cn，辛苦！

**Comment by hnx1223** [comment]
谢谢您的耐心解答！我检查出错误了，是我粗心了。你的代码很棒！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ChanglongJiangGit/A2J-Transformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月20日(星期三) 下午4:37
***@***.***&gt;;
抄送:&nbsp;"Nanxuan ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ChanglongJiangGit/A2J-Transformer] create datalist error (Issue #15)





 
还是没有收到，可能是github的邮箱问题，您直接在github ***@***.***，辛苦！

**Comment by ChanglongJiangGit** [comment]
好的，感谢关注！
